#!/bin/bash

set -o errexit \
    -o pipefail \
    -o nounset

# Checks the year-based ACLs to see whether a user has reapplied
# for their RC accounts that session.

# use own username if none supplied as argument
username=${1:-$USER}

RESET="$(tput sgr0)"
RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
BLUE="$(tput setaf 4)"
B_RED="$(tput setaf 9)"
B_GREEN="$(tput setaf 10)"
B_YELLOW="$(tput setaf 11)"
B_BLUE="$(tput setaf 12)"

COLOR_ERROR="${UCLRC_COLOR_ERROR:-${RED}}"
COLOR_INFO="${UCLRC_COLOR_INFO:-${BLUE}}"
COLOR_WARN="${UCLRC_COLOR_WARN:-${YELLOW}}"
COLOR_PASS="${UCLRC_COLOR_PASS:-${GREEN}}"
COLOR_FAIL="${UCLRC_COLOR_FAIL:-${RED}}"

function _warn() {
    echo "${COLOR_WARN}$*${RESET}"
}
function _error() {
    echo "${COLOR_ERROR}$*${RESET}"
}
function _info() {
    echo "${COLOR_INFO}$*${RESET}"
}
function _fail() {
    echo "${COLOR_FAIL}$*${RESET}"
}

function _palette() {
    echo "Palette:"
    echo " ${RED}Red${RESET}"
    echo " ${GREEN}Green${RESET}"
    echo " ${YELLOW}Yellow${RESET}"
    echo " ${BLUE}Blue${RESET}"
    echo " ${B_RED}Bold Red${RESET}"
    echo " ${B_GREEN}Bold Green${RESET}"
    echo " ${B_YELLOW}Bold Yellow${RESET}"
    echo " ${B_BLUE}Bold Blue${RESET}"
    echo "==="
    echo " ${COLOR_ERROR}Error${RESET}"
    echo " ${COLOR_WARN}Warn${RESET}"
    echo " ${COLOR_INFO}Info${RESET}"
    echo " ${COLOR_PASS}Pass${RESET}"
    echo " ${COLOR_FAIL}Fail${RESET}"
    exit
}

# Special case to experiment with colours
if [[ "${1:-}" == "--palette" ]]; then
    _palette
fi

### Section: Identity

if [[ "$username" =~ ^[A-Z0-9]+$ ]]; then
    _warn "Warning: this username is uppercased. It may be a UPI, not a username."
    _warn "         It will be converted to lowercase."
    _warn "         (You may also see this when copy/pasting usernames from MyServices.)"
    old_username="$username"
    username="${old_username,,}"
    echo "Username converted to: ${COLOR_PASS}${username}${RESET}"
fi

if [[ "$username" =~ ^[^[:space:]]+@ucl\.ac\.uk$ ]]; then
    _warn "Warning: this username looks like an email address."
    _warn "         It will be checked and converted."

    echo -n "Can id email address: "
    id "$username" >/dev/null 2>/dev/null && echo "${COLOR_PASS}yes${RESET}" || echo "${COLOR_WARN}no${RESET}"
    old_username="$username"
    if username="$(id -un "$username")"; then
        echo "Username converted successfully to: ${COLOR_PASS}${username}${RESET}"
    else
        _warn "Could not convert email address to username, leaving as-is."
        username="${old_username}"
    fi
fi

echo -n "Can id user: "
id "$username" >/dev/null 2>/dev/null && echo "${COLOR_PASS}yes${RESET}" || echo "${COLOR_FAIL}no${RESET}"


echo -n "User is in groups: "
if user_groups="$(groups "$username" 2>&1)"
then
    echo "${COLOR_PASS}${user_groups#*:}${RESET}"
else
    echo "${COLOR_FAIL}${user_groups#groups: *:}${RESET}"
fi

echo "" # Blank line for section separation

### Section: Scheduler Registration

function sge_check_acls() {
    local access_group
    local access_group_label
    local -a sge_access_groups sge_access_group_labels

    sge_access_groups+=(AY201617)
    sge_access_group_labels+=("access group for 2016-2017")
    sge_access_groups+=(AY201718)
    sge_access_group_labels+=("access group for 2017-2018")
    sge_access_groups+=(AY201819)
    sge_access_group_labels+=("access group for 2018-2019")
    sge_access_groups+=(Open)
    sge_access_group_labels+=("Open access group")

    for (( access_group_index=0; access_group_index < "${#sge_access_groups[@]}"; access_group_index++ )); do
        access_group="${sge_access_groups[$access_group_index]}"
        access_group_label="${sge_access_group_labels[$access_group_index]}"

        echo -n "Checking whether user is in $access_group_label: "
        if qconf -su "$access_group" 2>/dev/null >/dev/null; then
            if qconf -su "$access_group" | grep -q "$username"
            then
              echo "${COLOR_PASS}yes${RESET}"
            else
              echo "${COLOR_FAIL}no${RESET}"
            fi
        else
            echo "${COLOR_INFO}no such group${RESET}"
        fi
    done
}

function sge_check_nosub() {
    local username="$1"
    echo -n "Checking whether user has been blocked from submitting jobs: "
    if qconf -su NoSubmission 2>/dev/null >/dev/null
    then
        # check NoSubmission for blocked users
        if qconf -su NoSubmission | grep -q "$username"
        then
          echo "${COLOR_FAIL}yes${RESET}"
        else
          echo "${COLOR_PASS}no${RESET}"
        fi
    else
        echo "${COLOR_PASS}no (no blocked ACL here)${RESET}"
    fi
}

function slurm_check_user_exists() {
    local username="$1"
    echo -n "Checking whether user is in Slurm DB: "
    command -v jq >/dev/null || echo "${COLOR_FAIL}could not check, jq not found${RESET}"
    if sacctmgr --json list user "$username" \
        | jq -er '.users[].name' >/dev/null
    then
        echo "${COLOR_PASS}yes${RESET}"
    else
        echo "${COLOR_FAIL}no${RESET}"
    fi
}

function slurm_check_accounts() {
    local username="$1"
    local account
    local account_desc
    local -a check_accounts=(allusers)
    local user_accounts
          user_accounts="$(sacctmgr show assoc where user="$username" --noheader format='account%-40')"

    for account in "${check_accounts[@]}"; do
        account_desc="$(sacctmgr show account "$account" --json | jq -r '.accounts[].description')"
        echo -n "Checking whether user is in account ${account} (${account_desc}): "
        if grep -F -qw "${account}" <<< "${user_accounts}"; then
            echo "${COLOR_PASS}yes${RESET}"
        else
            echo "${COLOR_FAIL}no${RESET}"
        fi
    done
}

function slurm_check_nosub () {
    local username="$1"
    local account='allusers'
    local maxsubmitjob

    echo -n "Checking whether user has been blocked from submitting jobs: "
    maxsubmitjob="$(sacctmgr show assoc --noheader --parsable2 \
        where account="$account" user="$username" format='maxsubmitjob')"
    if [[ "$maxsubmitjob" == '0' ]]; then
        echo "${COLOR_FAIL}yes${RESET}"
    else
        echo "${COLOR_PASS}no${RESET}"
    fi
}

function sge_check_access () {
    local username="$1"
    local pam_listfile="/var/opt/sge/shared/userlist"

    echo -n "Checking whether user is in the actual PAM userlist: "
    if [[ ! -r "$pam_listfile" ]]; then
        echo "${COLOR_FAIL}error${RESET}"
        return
    fi
    if grep "^$username\$" "$pam_listfile" >/dev/null; then
        echo "${COLOR_PASS}yes${RESET}"
    else
        echo "${COLOR_FAIL}no${RESET}"
    fi
}

function slurm_check_access () {
    local username="$1"
    local pag
    local user_groups
    local clustername
          clustername="$(/shared/ucl/sysops/libexec/clustname 2>/dev/null || true)"

    echo -n "Checking whether user is in the platform access group: "
    if [[ -z "$clustername" ]]; then
        echo "${COLOR_FAIL}cannot determine cluster${RESET}"
        return
    fi
    case "$clustername" in
        myriad)   pag='pag-archpc-myriad' ;;
        kathleen) pag='pag-archpc-kathleen' ;;
        young)    pag='pag-archpc-young' ;;
        michael)  pag='pag-archpc-michael' ;;
        dev-*)    pag='pag-archpc-hydra' ;;
        *)
            echo "${COLOR_FAIL}unknown cluster \"$clustername\"${RESET}"
            return
            ;;
    esac
    if user_groups="$(groups "$username" 2>&1)"; then
        user_groups="${user_groups#*:}"
        if grep -F -qw "$pag" <<< "$user_groups"; then
            echo "${COLOR_PASS}yes${RESET} ($pag)"
        else
            echo "${COLOR_FAIL}no${RESET}"
        fi
    else
        echo "${COLOR_FAIL}no${RESET}"
    fi
}

function get_user_scratch_dir () {
    local username="$1"
    local clustername
          clustername="$(/shared/ucl/sysops/libexec/clustname 2>/dev/null || true)"

    case "$clustername" in
        myriad)   scratch_dir="/home/${username}/Scratch" ;;
        *)        scratch_dir="/scratch/scratch/${username}" ;;
    esac
    echo "${scratch_dir}"
}

have_sge=""
have_slurm=""
if command -v qconf >/dev/null; then
    have_sge='yes'
elif command -v sacctmgr >/dev/null; then
    have_slurm='yes'
fi


if [[ -n "$have_sge" ]]; then
    sge_check_acls "$username"
    sge_check_nosub "$username"
    sge_check_access "$username"
elif [[ -n "$have_slurm" ]]; then
    slurm_check_user_exists "$username"
    slurm_check_accounts "$username"
    slurm_check_nosub "$username"
    slurm_check_access "$username"
fi


echo "" # Blank line for section separation


### Section: Filesystems

# These skip checks that depend on certain dirs existing
flag_has_no_homedir=n
flag_has_no_scratch=n
flag_has_no_acfs=n

user_scratch_dir=$(get_user_scratch_dir "$username")

echo -n "Checking whether user has a home directory: "
if stat --printf='' "/home/${username}" 2>/dev/null
then
  echo "${COLOR_PASS}yes${RESET}"
else
  echo "${COLOR_FAIL}no${RESET}"
  flag_has_no_homedir=y
fi

echo -n "Checking whether user has a scratch directory: "
# On clusters with no discrete scratch FS, ordinary users
#  can't stat other users' scratch directories
if [[ -x "$(dirname "$user_scratch_dir")" ]]
then
    echo "${COLOR_INFO}inaccessible, skipped${RESET}"
    flag_has_no_scratch="y"
elif stat --printf='' "${user_scratch_dir}" 2>/dev/null
then
  echo "${COLOR_PASS}yes${RESET}"
else
  echo "${COLOR_FAIL}no${RESET}"
  flag_has_no_scratch=y
fi

echo -n "Checking whether user has an acfs directory: "
if stat --printf='' "/acfs/users/${username}" 2>/dev/null
then
    echo "${COLOR_PASS}yes${RESET}"
else
    echo "${COLOR_FAIL}no${RESET}"
    flag_has_no_acfs=y
fi

echo -n "Checking whether home directory is *owned* by that user: "
if [[ "$flag_has_no_homedir" == "n" ]]; then
    owner="$(stat --printf=%U "/home/${username}" 2>/dev/null)"
    if [[ "$owner" == "$username" ]]
    then
        echo "${COLOR_PASS}yes${RESET}"
    else
        echo "${COLOR_FAIL}no${RESET}"
    fi
else
    echo "${COLOR_INFO}skipped${RESET}"
fi

echo -n "Checking whether scratch directory is *owned* by that user: "
if [[ "$flag_has_no_scratch" == "n" ]]
then
    owner="$(stat --printf=%U "${user_scratch_dir}" 2>/dev/null)"
    if [[ "$owner" == "$username" ]]
    then
        echo "${COLOR_PASS}yes${RESET}"
    else
        echo "${COLOR_FAIL}no${RESET}"
    fi
else
    echo "${COLOR_INFO}skipped${RESET}"
fi

echo -n "Checking whether acfs directory is *owned* by that user: "
if [[ "$flag_has_no_acfs" == "n" ]]; then
    owner="$(stat --printf=%U "/acfs/users/${username}" 2>/dev/null)"
    if [[ "$owner" == "$username" ]]
    then
        echo "${COLOR_PASS}yes${RESET}"
    else
        echo "${COLOR_FAIL}no${RESET}"
    fi
else
    echo "${COLOR_INFO}skipped${RESET}"
fi


echo -n "Checking whether home directory is usable by owner: "
if [[ "$flag_has_no_homedir" == "n" ]]; then
    perms="$(stat --printf=%A "/home/${username}" 2>/dev/null)"
    if [[ "${perms:1:3}" =~ rwx ]]
    then
        echo "${COLOR_PASS}yes${RESET}"
    else 
        echo "${COLOR_FAIL}no: perms are ${perms}${RESET}"
    fi
else
    echo "${COLOR_INFO}skipped${RESET}"
fi

echo -n "Checking whether scratch directory is usable by owner: "
if [[ "$flag_has_no_scratch" == "n" ]]
then
    perms="$(stat --printf=%A "${user_scratch_dir}" 2>/dev/null)"
    if [[ "${perms:1:3}" =~ rwx ]];
    then
        echo  "${COLOR_PASS}yes${RESET}"
    else 
        echo "${COLOR_FAIL}no: perms are ${perms}${RESET}"
    fi
else
    echo "${COLOR_INFO}skipped${RESET}"
fi

echo -n "Checking whether acfs directory is usable by owner: "
if [[ "$flag_has_no_acfs" == "n" ]]; then
    perms="$(stat --printf=%A "/acfs/users/${username}" 2>/dev/null)"
    if [[ "${perms:1:3}" =~ rwx ]]
    then
        echo "${COLOR_PASS}yes${RESET}"
    else 
        echo "${COLOR_FAIL}no: perms are ${perms}${RESET}"
    fi
else
    echo "${COLOR_INFO}skipped${RESET}"
fi

echo -n "Checking whether home directory has standard permissions: "
if [[ "$flag_has_no_homedir" == "n" ]]; then
    perms="$(stat --printf=%A "/home/${username}" 2>/dev/null)"
    if [[ "${perms}" == "drwx------" ]];
    then
        echo "${COLOR_PASS}yes${RESET}"
    else 
        echo "${COLOR_FAIL}no: perms are ${perms}${RESET}"
    fi
else
    echo "${COLOR_INFO}skipped${RESET}"
fi

### Section: User Activity

echo ""

function sge_check_jobs () {
    local username="$1"
    echo -n "Checking whether user has jobs in the queue: "
    num_jobs="$(qstat -u "$username" | wc -l)"
    if [[ "$num_jobs" -gt 0 ]]; then
        echo "${COLOR_PASS}yes${RESET}"
    else
        echo "${COLOR_INFO}no${RESET}"
    fi
}

function slurm_check_jobs () {
    local username="$1"
    echo -n "Checking whether user has jobs in the queue: "
    num_jobs="$(squeue --noheader --user="$username" --Format='JobID' 2>/dev/null | wc -l)"
    if [[ "$num_jobs" -gt 0 ]]; then
        echo "${COLOR_PASS}yes${RESET}"
    else
        echo "${COLOR_INFO}no${RESET}"
    fi
}

if [[ -n "$have_sge" ]]; then
    sge_check_jobs "$username"
elif [[ -n "$have_slurm" ]]; then
    slurm_check_jobs "$username"
fi

echo -n "Checking when user last logged in to this node: "
last_login="$(last -adwn 1 "${username}" | head -n 1)"
if [[ -z "$last_login" ]]; then
    echo "${COLOR_FAIL}never${RESET}"
else
    echo "${COLOR_INFO}$last_login${RESET}"
fi

