#!/usr/bin/env bash

set -o errexit \
    -o nounset \
    -o pipefail

function usage () {
    echo "
    Usage: $0 JOBID
    
    Prints the job script for the given JOBID to stdout.
    "
}

# source common functions
scriptfile="$(realpath "$0")"
scriptdir="${scriptfile%/*}"
. "${scriptdir}/functions.sh"


jobid="${1-}"

if [[ -z "$jobid" ]]; then
    usage
    exit 1
fi

if ! slurm_am_operator; then
   echo "ERROR: You must be a Slurm Operator to see other users' scripts." >&2
   exit 1
fi

sacct --batch-script --jobs="$jobid" \
| tail -n +3
