#!/usr/bin/env bash

set -o errexit \
    -o nounset \
    -o pipefail

function usage () {
    echo "
    Usage: $0 JOBID
    
    Prints the job script for the given JOBID to stdout.
    "
}

function amOperator() {
    local adminLevel
    adminLevel="$(sacctmgr show user "$USER" --noheader --parsable2 | cut -d'|' -f3)"
    case "${adminLevel}" in
        Operator|Administrator)
            return 0 ;;
        *)
            return 1 ;;
    esac
}


jobid="${1-}"

if [[ -z "$jobid" ]]; then
    usage
    exit 1
fi

if ! amOperator; then
   echo "ERROR: You must be a Slurm Operator to see other users' scripts." >&2
   exit 1
fi

sacct --batch-script --jobs="$jobid" \
| tail -n +3
